# Generated by Django 4.0.4 on 2022-05-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='content',
        ),
    ]
